### PR TITLE
Update project to run modern Conan

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by theirix** [comment]
Looks good, great work!

CIs are passing except the appveyor glitch.

Small improvements:
- test_package/conanfile.py can be copied entirely from templates
- appveyor.yml - is the `VS150COMNTOOLS` needed at all? I do not know
- seems you forgot the ` exports = ["LICENSE.md"]`
- README.md - please replace copy-pasted libpcap reference
- README.md - pkg_name
- README.md - typos `publi-conan`, `libsub`

**Comment by uilianries** [comment]
Thanks for review! I'll update later!

Regards!

**Comment by uilianries** [comment]
- [x]  test_package/conanfile.py can be copied entirely from templates
- [x]  appveyor.yml - is the VS150COMNTOOLS needed at all? I do not know
- [x]  seems you forgot the exports = ["LICENSE.md"]
- [x]  README.md - please replace copy-pasted libpcap reference
- [x]  README.md - pkg_name
- [x]  README.md - typos publi-conan, libsub

**Review by theirix — APPROVED** [review]
Reviewed latest changes. LGTM!

**Pull request merged**
